version: '3.8'
name: api-gateway-backend
services:
  postgres:
    image: "postgres:17.6"
    container_name: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5432:5432"
  user-service:
    container_name: user-service
    image: 049139783164.dkr.ecr.us-east-1.amazonaws.com/develop/user-service:1.0.13
    volumes:
      - ./configs/user-config.yaml:/etc/user-service/config.yaml
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
  orders-service:
    container_name: orders-service
    image: 049139783164.dkr.ecr.us-east-1.amazonaws.com/develop/orders-service:1.0.7
    volumes:
      - ./configs/orders-config.yaml:/etc/orders-service/config.yaml
    ports:
      - "8100:8100"
    depends_on:
      postgres:
        condition: service_healthy
  product-service:
    container_name: product-service
    image: 049139783164.dkr.ecr.us-east-1.amazonaws.com/develop/product-service:1.0.14
    volumes:
      - ./configs/product-config.yaml:/etc/product-service/config.yaml
    ports:
      - "8200:8200"
    depends_on:
      postgres:
        condition: service_healthy
