# configs/config.yaml
environment: development

version: 1.0.0

server:
  port: "8100"
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  cors:
    allow_origins: ["*"]

database:
  host: "localhost"
  port: "5432"
  username: "api-gateway"
  password: "admin"
  database: "api-gateway"
  ssl_mode: "disable"

security:
  rate_limit_rps: 100
  rate_limit_burst: 200

logging:
  level: "debug"
  format: "text"