environment: development

version: 1.0.0

server:
  port: "8300"
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  path_prefix: "/api"
  cors:
    allow_origins: ["*"]

redis:
  host: "localhost"
  port: "6379"
  password: ""
  database: 0

backends:
  - host: "http://localhost:8000"
    id: "user"
    path_prefix: "/api/v1"
    routes:
      - id: "user-health"
        method: "GET"
        path: "/health"
        path_type: "exact"
        enabled: "true"
        auth_policy:
          type: "none"
          enabled: "true"

      - id: "user-health-ready"
        method: "GET"
        path: "/health/ready"
        path_type: "exact"
        enabled: "true"
        auth_policy:
          type: "none"
          enabled: "true"

      - id: "user-health-live"
        method: "GET"
        path: "/health/live"
        path_type: "exact"
        enabled: "true"
        auth_policy:
          type: "none"
          enabled: "true"

      - id: "user-metrics"
        method: "GET"
        path: "/metrics"
        path_type: "exact"
        enabled: "true"
        auth_policy:
          type: "none"
          enabled: "true"

      - id: "user-create"
        method: "POST"
        path: "/users"
        path_type: "exact"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

      - id: "user-list"
        method: "GET"
        path: "/users"
        path_type: "exact"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

      - id: "user-get-by-email"
        method: "GET"
        path: "/users/email/:email"
        path_type: "prefix"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

      - id: "user-get-by-id"
        method: "GET"
        path: "/users/:id"
        path_type: "prefix"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

  - host: "http://localhost:8100"
    id: "orders"
    path_prefix: "/api/v1"
    routes:
      - id: "orders-health"
        method: "GET"
        path: "/health"
        path_type: "exact"
        enabled: "true"
        auth_policy:
          type: "none"
          enabled: "true"

      - id: "orders-health-ready"
        method: "GET"
        path: "/health/ready"
        path_type: "exact"
        enabled: "true"
        auth_policy:
          type: "none"
          enabled: "true"

      - id: "orders-health-live"
        method: "GET"
        path: "/health/live"
        path_type: "exact"
        enabled: "true"
        auth_policy:
          type: "none"
          enabled: "true"

      - id: "orders-metrics"
        method: "GET"
        path: "/metrics"
        path_type: "exact"
        enabled: "true"
        auth_policy:
          type: "none"
          enabled: "true"

      - id: "orders-create"
        method: "POST"
        path: "/orders"
        path_type: "exact"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

      - id: "orders-list"
        method: "GET"
        path: "/orders"
        path_type: "exact"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

      - id: "orders-by-customer"
        method: "GET"
        path: "/customers/:customer_id/orders"
        path_type: "prefix"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

      - id: "orders-get-by-status"
        method: "GET"
        path: "/orders/status/:status"
        path_type: "prefix"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

      - id: "orders-confirm"
        method: "POST"
        path: "/orders/:id/confirm"
        path_type: "prefix"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

      - id: "orders-cancel"
        method: "POST"
        path: "/orders/:id/cancel"
        path_type: "prefix"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

      - id: "orders-add-item"
        method: "POST"
        path: "/orders/:id/items"
        path_type: "prefix"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

      - id: "orders-update-item"
        method: "PUT"
        path: "/orders/:id/items/:product_id"
        path_type: "prefix"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

      - id: "orders-remove-item"
        method: "DELETE"
        path: "/orders/:id/items/:product_id"
        path_type: "prefix"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

      - id: "orders-update-status"
        method: "PUT"
        path: "/orders/:id/status"
        path_type: "prefix"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

      - id: "orders-get-by-id"
        method: "GET"
        path: "/orders/:id"
        path_type: "prefix"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

      - id: "orders-delete"
        method: "DELETE"
        path: "/orders/:id"
        path_type: "prefix"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

  - host: "http://localhost:8200"
    id: "product"
    path_prefix: "/api/v1"
    routes:
      - id: "product-health"
        method: "GET"
        path: "/health"
        path_type: "exact"
        enabled: "true"
        auth_policy:
          type: "none"
          enabled: "true"

      - id: "product-health-ready"
        method: "GET"
        path: "/health/ready"
        path_type: "exact"
        enabled: "true"
        auth_policy:
          type: "none"
          enabled: "true"

      - id: "product-health-live"
        method: "GET"
        path: "/health/live"
        path_type: "exact"
        enabled: "true"
        auth_policy:
          type: "none"
          enabled: "true"

      - id: "product-metrics"
        method: "GET"
        path: "/metrics"
        path_type: "exact"
        enabled: "true"
        auth_policy:
          type: "none"
          enabled: "true"

      - id: "product-create"
        method: "POST"
        path: "/products"
        path_type: "exact"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

      - id: "product-list"
        method: "GET"
        path: "/products"
        path_type: "exact"
        enabled: "true"
        auth_policy:
          type: "none"
          enabled: "true"

      - id: "product-get-by-sku"
        method: "GET"
        path: "/products/sku/:sku"
        path_type: "prefix"
        enabled: "true"
        auth_policy:
          type: "none"
          enabled: "true"

      - id: "product-update-stock"
        method: "PATCH"
        path: "/products/:id/stock"
        path_type: "prefix"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

      - id: "product-update-price"
        method: "PATCH"
        path: "/products/:id/price"
        path_type: "prefix"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

      - id: "product-activate"
        method: "PATCH"
        path: "/products/:id/activate"
        path_type: "prefix"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

      - id: "product-deactivate"
        method: "PATCH"
        path: "/products/:id/deactivate"
        path_type: "prefix"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

      - id: "product-discontinue"
        method: "PATCH"
        path: "/products/:id/discontinue"
        path_type: "prefix"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

      - id: "product-get-by-id"
        method: "GET"
        path: "/products/:id"
        path_type: "prefix"
        enabled: "true"
        auth_policy:
          type: "none"
          enabled: "true"

      - id: "product-update"
        method: "PUT"
        path: "/products/:id"
        path_type: "prefix"
        enabled: "true"
        auth_policy:
          type: "api"
          enabled: "true"

security:
  rate_limit_rps: 100
  rate_limit_burst: 200

logging:
  level: "debug"
  format: "text"