# configs/config.yaml
environment: development

version: 1.0.0

server:
  port: "8300"
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  cors:
    allow_origins: ["*"]

redis:
  host: "localhost"
  port: "6379"
  password: ""
  database: 0

backends:
  - host: "http://localhost:8000"
    id: "user"
    path_prefix: "/api/v1/"
    routes:
      - id: "ready"
        method: "GET"
        path: "health/ready"
        path_type: "exact"
        enabled: "true"
        auth_policy:
          type: "none"
          enabled: "true"
  - host: "http://localhost:8100/api/v1/orders"
    id: "orders"
    path_prefix: "/api/v1/"
    strip_prefix: "/api/v1/orders"
    routes:
      - id: "ready"
        method: "GET"
        path: "/health/ready"
        path_type: "exact"
        enabled: "true"
        auth_policy:
          type: "none"
          enabled: "true"
  - host: "http://localhost:8200/api/v1/"
    id: "product"
    routes:
      - id: "ready"
        method: "GET"
        path: "/health/ready"
        path_type: "exact"
        enabled: "true"
        auth_policy:
          type: "none"
          enabled: "true"


security:
  rate_limit_rps: 100
  rate_limit_burst: 200

logging:
  level: "debug"
  format: "text"